## 5.4 동적크롤링

reference: https://selenium-python.readthedocs.io/index.html

In [2]:
!pip install selenium #selenium 설치

Collecting selenium
  Downloading selenium-4.4.3-py3-none-any.whl (985 kB)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\user\anaconda3\lib\site-packages (from selenium) (1.26.7)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\user\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Collecting trio~=0.17
  Downloading trio-0.21.0-py3-none-any.whl (358 kB)
Requirement already satisfied: async-generator>=1.9 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sortedcontainers in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.6)
Requirement already satisfied: sniffio in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Collecting outcome
  Downloading outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Requirement already satisfied: attrs>=19.2.0 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: idna in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.2)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Collecting wsproto>=0.14
  Downloading wsproto-1.1.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\user\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Collecting h11<1,>=0.9.0
  Downloading h11-0.13.0-py3-none-any.whl (58 kB)
Installing collected packages: outcome, h11, wsproto, trio, trio-websocket, selenium
Successfully installed h11-0.13.0 outcome-1.2.0 selenium-4.4.3 trio-0.21.0 trio-websocket-0.9.2 wsproto-1.1.0

In [3]:
from selenium import webdriver

### 5.4.1 설치 방법

```cmd
pip install selenium
```

Chrome Driver: https://chromedriver.chromium.org/downloads

In [4]:
# 크롬 설정에 들어가서 chrome 정보 확인 (버전정보를 보여줌)
# 해당정보로 win 32 zip 설정

### 5.4.2 사용법

기본적인 사용 방법은 아래와 같음
```python
from selenium import webdriver
 
driver = webdriver.Chrome(executable_path='chromedriver') # executable_path: chromedriver path
# driver = webdriver.Firefox()

driver.get(url="http://www.naver.com")

driver.close()
```

#### 5.4.2.1 Locating Elements

find_element: 조건에 해당하는 하나의 값 반환  
find_elements: 조건에 해당하는 다수의 값 반환

element를 찾는 method는 아래와 같음
- by_ID
- by_xpath
- by_link_text
- by_partial_link_text
- by_name
- by_tag_name
- by_class_name
- by_css_selector

```python
from selenium.webdriver.common.by import By
element = driver.find_element(By.XPATH, x_path)
element = driver.find_element_by_xpath(x_path)

element = driver.find_element(By.CSS_SELECTOR, css)
element = driver.find_element_by_css_selector(css)
```

해당 값을 못 찾은 경우 NoSuchElementException 발생

#### 5.4.2.2 Navigating

###### Send Keys
```python
driver.find_element_by_xpath(xpath).send_keys(id)
driver.find_element_by_xpath(xpath).send_keys(password)
driver.find_element_by_xpath(xpath).click()
```

외에도 Keys 내의 다양한 커맨드 입력 가능
```
from selenium.webdriver.common.keys import Keys
```
|Command          |Action |
|-----------------|-------|
|Keys.ENTER       |엔터    |
|Keys.RRETURN     |       |
|Keys.SPACE       |스페이스 |
|Keys.ARROW_UP    |화살표   |
|Keys.ARROW_DOWN  |       |
|Keys.ARROW_LEFT  |       |
|Keys.ARROW_RIGHT |       |
|Keys.BACK_SPACE  |지우기   |
|Keys.DELETE      |       |
|Keys.CONTROL     |Ctrl   |
|Keys.ALT         |Alt    |
|Keys.SHIFT       |Shift  |
|Keys.TAB         |Tab    |
|Keys.PAGE_UP     |Page-Up|
|Keys.PAGE_DOWN   |Page-Down|
|Keys.TAB         |Tab    |
|Keys.F1 ~ Keys.F9|F1~F9  |
|Keys.ESCAPE      |ESC    |
|Keys.HOME        |Home   |
|Keys.INSERT      |Insert |
|...              |...    |

##### Drag and Drop

```python
from selenium.webdriver import ActionChains

element = driver.find_element(By.NAME, "source")
target = driver.find_element(By.NAME, "target")

action_chains = ActionChains(driver)
action_chains.drag_and_drop(element, target).perform()
```

##### Moving between Windows
```python
previous_window = driver.window_handles[0]
new_window = driver.window_handles[1]
driver.switch_to.window(new_window)
```

##### Moving
```python
driver.forward()
driver.back()
```

#### 5.4.2.3 Waiting

Selenium은 실행 중인 driver를 이용하여 정보를 추출  
driver에 데이터 로딩이 완료되지 않을 경우 데이터 수집이 불가  
따라서 페이지 이동 등의 작업이 들어가면 다음 작업이 완료될 때까지 대기해야만 함

##### Time

가장 기본적인 방법으로 대기 시간을 time 모듈을 통해 명시

```python
import time
from selenium import webdriver


driver = webdriver.Chrome(executable_path='chromedriver')
driver.get(url="http://www.naver.com")
time.sleep(5)
driver.close()
```

##### Implicit Wait

위의 time에서는 2가지 문제가 존재
1. 모든 반응형 동작마다 time을 걸어 웹 로딩 대기
2. time을 5초로 설정했지만 실제 그보다 동작이 빨리 끝날 경우 불필요한 시간 대기

위의 문제를 해결하고자 implicit wait을 이용  
이는 driver의 옵션 설정으로 반응형 동작에서 최대 허용 대기 시간을 설정  
만약 허용 시간 이내에 로드가 완료될 경우 다음 작업을 바로 진행

```python
from selenium import webdriver


driver = webdriver.Chrome(executable_path='chromedriver')
driver.implicitly_wait(time_to_wait=5)
driver.get(url="http://www.naver.com")
driver.close()

```

##### Explicit Wait

implicit wait에서는 driver가 로딩을 대기하는 시간을 설정하여 5초를 설정하였어도 이전에 로드가 완료되면 다음 작업의 진행이 가능하였음  
하지만 위 경우도 문제가 있는데 5초가 지나도 내가 원하는 데이터가 로드가 안 되었을 경우 데이터를 수집할 수 없음  
따라서 특정 값이 로드될 때까지 기다렸다가 그 값이 로드되면 다음 작업을 진행할 필요성이 발생  
이 때 이용하는 게 explicit wait

```python
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome(executable_path='chromedriver') 
driver.get(url="http://www.naver.com")

try:
    element = WebDriverWait(driver, 5).until(
        EC.presence_of_element_located((By.CLASS_NAME , 'paging'))
    )
finally:
    driver.quit()

driver.close()

```

until: 조건이 False인 동안에 계속 실행  
not_until: 조건이 True인 동안에 계속 실행

#### 5.4.2.4 ActionChains

연속 동작을 수행하기 위함

ex) control + c
```python
ActionChains(driver).key_down(Keys.CONTROL).send_keys('c').key_up(Keys.CONTROL).perform()
```

##### Drag and Drop

```python
from selenium.webdriver import ActionChains

element = driver.find_element(By.NAME, "source")
target = driver.find_element(By.NAME, "target")

action_chains = ActionChains(driver)
action_chains.drag_and_drop(element, target).perform()
```

#### 5.4.2.5 Others

##### Options
```python
options = webdriver.ChromeOptions()
options.add_argument('window-size=1920,1080')

driver = webdriver.Chrome(executable_path, options=options)
```

##### Alert

경고창 발생 시 이에 수락, 거절 등의 행동을 취할 수 있음

```python
from selenium.webdriver.common.alert import Alert

Alert(driver).accept() # 수락
Alert(driver).dismiss() # 거절
Alert(driver).send_keys(keysToSend=key) # 특정 키를 보낼 수 있음
```

##### Scroll Down
페이지의 최하단으로 이동
```python
driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
```
<br>

특정 태그가 등장할 때까지 이동
```python
from selenium.webdriver import ActionChains

some_tag = driver.find_element_by_id('gorio')
ActionChains(driver).move_to_element(some_tag).perform()
```

##### Minimize/Maximize

```python
driver.minimize_window()
driver.maximize_window()
```

##### Screen Shot
```python
driver.save_screenshot('screenshot.png')
```

#### 실습

##### gmail log-in

In [57]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

In [60]:

driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더
# driver = webdriver.Firefox()
driver.get(url="http://www.naver.com")

# driver.close()

C:\Users\user\AppData\Local\Temp/ipykernel_24008/1278096618.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더

In [24]:
driver.close()

In [25]:
driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더
# driver = webdriver.Firefox()

driver.get(url="http://www.gmail.com")

C:\Users\user\AppData\Local\Temp/ipykernel_24008/3038828338.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더

In [26]:

driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[1]/div/div[1]/div/div[1]/input').send_keys('larryha89')

In [27]:
driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div/div/button/span').click()

In [ ]:
driver.close()

##### naver log-in

In [39]:

driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더
# driver = webdriver.Firefox()

driver.get(url="http://www.naver.com")

# driver.close()

C:\Users\user\AppData\Local\Temp/ipykernel_24008/1768975853.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더

In [40]:
driver.find_element(By.XPATH, '/html/body/div[2]/div[3]/div[3]/div/div[2]/a').click()

In [41]:
driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/div[1]/form/ul/li/div/div[1]/div[1]/input').send_keys('qzom89')

In [42]:
driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/div[1]/form/ul/li/div/div[1]/div[2]/input').send_keys('sjftkfkdgo')

In [43]:
driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/div[1]/form/ul/li/div/div[7]/button').click()

### 5.4.3.2 기업집단 포털

#### 브라우저 내에 가져올수 없는 내역을 selenium을 통하셔 사용한다

In [ ]:
https://www.egroup.go.kr/egps/wi/stat/kap/affltsAssetsTotamtList.do

In [63]:
driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더
driver.get(url="https://www.egroup.go.kr/egps/wi/stat/kap/affltsAssetsTotamtList.do")
time.sleep(4) #드라이버 로드까지 걸리는 초단위
bs = BeautifulSoup(driver.page_source, 'lxml')  #페이지에 있는 모든소스를 가져온다
driver.close()

C:\Users\user\AppData\Local\Temp/ipykernel_24008/75710216.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더

In [64]:
bs.select('div#resultListDiv')[0].select('tr') #selenium은 모든 페이지의 내용을 가져올수있다

[<tr>
 <th rowspan="2" scope="colgroup">구분</th>
 <th rowspan="2" scope="colgroup">기업집단명</th>
 <th rowspan="2" scope="colgroup">동일인</th>
 <th colspan="3" scope="colgroup">계열회사 수</th>
 <th colspan="3" scope="colgroup">자산총액</th>
 </tr>,
 <tr>
 <th scope="colgroup">202205</th>
 <th scope="colgroup">202105</th>
 <th scope="colgroup">증감</th>
 <th scope="colgroup">202205</th>
 <th scope="colgroup">202105</th>
 <th scope="colgroup">증감</th>
 </tr>,
 <tr>
 <td name="gbnTd" rowspan="68">계속지정집단</td>
 <td style="text-align: left;">DB</td>
 <td style="text-align: left;">김준기</td>
 <td name="sumA_target" style="text-align: right;">20</td>
 <td name="sumB_target" style="text-align: right;">21</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">11,260</td>
 <td style="text-align: right;">10,366</td>
 <td style="text-align: right;">893</td>
 </tr>,
 <tr>
 <td style="text-align: left;">DL</td>
 <td style="text-align: left;">이준용</td>
 <td name="sumA_target" style="text-align: right;">42</td>
 <td name="sumB_target" style="text-align: right;">36</td>
 <td name="sumC_target" style="text-align: right;">6</td>
 <td style="text-align: right;">24,766</td>
 <td style="text-align: right;">19,627</td>
 <td style="text-align: right;">5,140</td>
 </tr>,
 <tr>
 <td style="text-align: left;">SM</td>
 <td style="text-align: left;">우오현</td>
 <td name="sumA_target" style="text-align: right;">63</td>
 <td name="sumB_target" style="text-align: right;">58</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">13,663</td>
 <td style="text-align: right;">10,450</td>
 <td style="text-align: right;">3,213</td>
 </tr>,
 <tr>
 <td style="text-align: left;">교보생명보험</td>
 <td style="text-align: left;">신창재</td>
 <td name="sumA_target" style="text-align: right;">14</td>
 <td name="sumB_target" style="text-align: right;">12</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">13,817</td>
 <td style="text-align: right;">14,413</td>
 <td style="text-align: right;">-596</td>
 </tr>,
 <tr>
 <td style="text-align: left;">금호석유화학</td>
 <td style="text-align: left;">박찬구</td>
 <td name="sumA_target" style="text-align: right;">13</td>
 <td name="sumB_target" style="text-align: right;">15</td>
 <td name="sumC_target" style="text-align: right;">-2</td>
 <td style="text-align: right;">9,608</td>
 <td style="text-align: right;">6,665</td>
 <td style="text-align: right;">2,943</td>
 </tr>,
 <tr>
 <td style="text-align: left;">금호아시아나</td>
 <td style="text-align: left;">박삼구</td>
 <td name="sumA_target" style="text-align: right;">32</td>
 <td name="sumB_target" style="text-align: right;">27</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">17,627</td>
 <td style="text-align: right;">17,442</td>
 <td style="text-align: right;">185</td>
 </tr>,
 <tr>
 <td style="text-align: left;">네이버</td>
 <td style="text-align: left;">이해진</td>
 <td name="sumA_target" style="text-align: right;">54</td>
 <td name="sumB_target" style="text-align: right;">45</td>
 <td name="sumC_target" style="text-align: right;">9</td>
 <td style="text-align: right;">19,220</td>
 <td style="text-align: right;">13,584</td>
 <td style="text-align: right;">5,636</td>
 </tr>,
 <tr>
 <td style="text-align: left;">넥슨</td>
 <td style="text-align: left;">유정현</td>
 <td name="sumA_target" style="text-align: right;">18</td>
 <td name="sumB_target" style="text-align: right;">18</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">11,261</td>
 <td style="text-align: right;">11,998</td>
 <td style="text-align: right;">-736</td>
 </tr>,
 <tr>
 <td style="text-align: left;">넷마블</td>
 <td style="text-align: left;">방준혁</td>
 <td name="sumA_target" style="text-align: right;">30</td>
 <td name="sumB_target" style="text-align: right;">23</td>
 <td name="sumC_target" style="text-align: right;">7</td>
 <td style="text-align: right;">13,303</td>
 <td style="text-align: right;">10,703</td>
 <td style="text-align: right;">2,600</td>
 </tr>,
 <tr>
 <td style="text-align: left;">농협</td>
 <td style="text-align: left;">농업협동조합중앙회</td>
 <td name="sumA_target" style="text-align: right;">53</td>
 <td name="sumB_target" style="text-align: right;">58</td>
 <td name="sumC_target" style="text-align: right;">-5</td>
 <td style="text-align: right;">66,962</td>
 <td style="text-align: right;">63,552</td>
 <td style="text-align: right;">3,411</td>
 </tr>,
 <tr>
 <td style="text-align: left;">다우키움</td>
 <td style="text-align: left;">김익래</td>
 <td name="sumA_target" style="text-align: right;">48</td>
 <td name="sumB_target" style="text-align: right;">45</td>
 <td name="sumC_target" style="text-align: right;">3</td>
 <td style="text-align: right;">8,505</td>
 <td style="text-align: right;">6,593</td>
 <td style="text-align: right;">1,912</td>
 </tr>,
 <tr>
 <td style="text-align: left;">대방건설</td>
 <td style="text-align: left;">구교운</td>
 <td name="sumA_target" style="text-align: right;">45</td>
 <td name="sumB_target" style="text-align: right;">43</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">6,184</td>
 <td style="text-align: right;">5,326</td>
 <td style="text-align: right;">858</td>
 </tr>,
 <tr>
 <td style="text-align: left;">대우조선해양</td>
 <td style="text-align: left;">대우조선해양(주)</td>
 <td name="sumA_target" style="text-align: right;">4</td>
 <td name="sumB_target" style="text-align: right;">5</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">11,415</td>
 <td style="text-align: right;">11,375</td>
 <td style="text-align: right;">39</td>
 </tr>,
 <tr>
 <td style="text-align: left;">동국제강</td>
 <td style="text-align: left;">장세주</td>
 <td name="sumA_target" style="text-align: right;">11</td>
 <td name="sumB_target" style="text-align: right;">11</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">6,711</td>
 <td style="text-align: right;">5,956</td>
 <td style="text-align: right;">754</td>
 </tr>,
 <tr>
 <td style="text-align: left;">동원</td>
 <td style="text-align: left;">김재철</td>
 <td name="sumA_target" style="text-align: right;">26</td>
 <td name="sumB_target" style="text-align: right;">26</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">9,281</td>
 <td style="text-align: right;">8,458</td>
 <td style="text-align: right;">823</td>
 </tr>,
 <tr>
 <td style="text-align: left;">두산</td>
 <td style="text-align: left;">박정원</td>
 <td name="sumA_target" style="text-align: right;">21</td>
 <td name="sumB_target" style="text-align: right;">22</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">26,334</td>
 <td style="text-align: right;">29,659</td>
 <td style="text-align: right;">-3,325</td>
 </tr>,
 <tr>
 <td style="text-align: left;">롯데</td>
 <td style="text-align: left;">신동빈</td>
 <td name="sumA_target" style="text-align: right;">85</td>
 <td name="sumB_target" style="text-align: right;">86</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">121,589</td>
 <td style="text-align: right;">117,781</td>
 <td style="text-align: right;">3,808</td>
 </tr>,
 <tr>
 <td style="text-align: left;">미래에셋</td>
 <td style="text-align: left;">박현주</td>
 <td name="sumA_target" style="text-align: right;">40</td>
 <td name="sumB_target" style="text-align: right;">38</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">20,231</td>
 <td style="text-align: right;">19,333</td>
 <td style="text-align: right;">897</td>
 </tr>,
 <tr>
 <td style="text-align: left;">반도홀딩스</td>
 <td style="text-align: left;">권홍사</td>
 <td name="sumA_target" style="text-align: right;">25</td>
 <td name="sumB_target" style="text-align: right;">28</td>
 <td name="sumC_target" style="text-align: right;">-3</td>
 <td style="text-align: right;">5,679</td>
 <td style="text-align: right;">5,585</td>
 <td style="text-align: right;">93</td>
 </tr>,
 <tr>
 <td style="text-align: left;">부영</td>
 <td style="text-align: left;">이중근</td>
 <td name="sumA_target" style="text-align: right;">22</td>
 <td name="sumB_target" style="text-align: right;">23</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">21,736</td>
 <td style="text-align: right;">23,321</td>
 <td style="text-align: right;">-1,585</td>
 </tr>,
 <tr>
 <td style="text-align: left;">삼성</td>
 <td style="text-align: left;">이재용</td>
 <td name="sumA_target" style="text-align: right;">60</td>
 <td name="sumB_target" style="text-align: right;">59</td>
 <td name="sumC_target" style="text-align: right;">1</td>
 <td style="text-align: right;">483,919</td>
 <td style="text-align: right;">457,305</td>
 <td style="text-align: right;">26,614</td>
 </tr>,
 <tr>
 <td style="text-align: left;">삼양</td>
 <td style="text-align: left;">김윤</td>
 <td name="sumA_target" style="text-align: right;">12</td>
 <td name="sumB_target" style="text-align: right;">11</td>
 <td name="sumC_target" style="text-align: right;">1</td>
 <td style="text-align: right;">6,247</td>
 <td style="text-align: right;">5,412</td>
 <td style="text-align: right;">835</td>
 </tr>,
 <tr>
 <td style="text-align: left;">삼천리</td>
 <td style="text-align: left;">이만득</td>
 <td name="sumA_target" style="text-align: right;">44</td>
 <td name="sumB_target" style="text-align: right;">42</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">8,551</td>
 <td style="text-align: right;">7,841</td>
 <td style="text-align: right;">709</td>
 </tr>,
 <tr>
 <td style="text-align: left;">세아</td>
 <td style="text-align: left;">이순형</td>
 <td name="sumA_target" style="text-align: right;">26</td>
 <td name="sumB_target" style="text-align: right;">29</td>
 <td name="sumC_target" style="text-align: right;">-3</td>
 <td style="text-align: right;">10,791</td>
 <td style="text-align: right;">9,470</td>
 <td style="text-align: right;">1,321</td>
 </tr>,
 <tr>
 <td style="text-align: left;">셀트리온</td>
 <td style="text-align: left;">서정진</td>
 <td name="sumA_target" style="text-align: right;">7</td>
 <td name="sumB_target" style="text-align: right;">8</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">14,576</td>
 <td style="text-align: right;">14,855</td>
 <td style="text-align: right;">-279</td>
 </tr>,
 <tr>
 <td style="text-align: left;">신세계</td>
 <td style="text-align: left;">이명희</td>
 <td name="sumA_target" style="text-align: right;">53</td>
 <td name="sumB_target" style="text-align: right;">45</td>
 <td name="sumC_target" style="text-align: right;">8</td>
 <td style="text-align: right;">61,055</td>
 <td style="text-align: right;">46,409</td>
 <td style="text-align: right;">14,645</td>
 </tr>,
 <tr>
 <td style="text-align: left;">씨제이</td>
 <td style="text-align: left;">이재현</td>
 <td name="sumA_target" style="text-align: right;">85</td>
 <td name="sumB_target" style="text-align: right;">79</td>
 <td name="sumC_target" style="text-align: right;">6</td>
 <td style="text-align: right;">36,925</td>
 <td style="text-align: right;">34,676</td>
 <td style="text-align: right;">2,249</td>
 </tr>,
 <tr>
 <td style="text-align: left;">아모레퍼시픽</td>
 <td style="text-align: left;">서경배</td>
 <td name="sumA_target" style="text-align: right;">13</td>
 <td name="sumB_target" style="text-align: right;">14</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">8,388</td>
 <td style="text-align: right;">8,009</td>
 <td style="text-align: right;">379</td>
 </tr>,
 <tr>
 <td style="text-align: left;">아이에스지주</td>
 <td style="text-align: left;">권혁운</td>
 <td name="sumA_target" style="text-align: right;">53</td>
 <td name="sumB_target" style="text-align: right;">46</td>
 <td name="sumC_target" style="text-align: right;">7</td>
 <td style="text-align: right;">5,343</td>
 <td style="text-align: right;">5,190</td>
 <td style="text-align: right;">153</td>
 </tr>,
 <tr>
 <td style="text-align: left;">애경</td>
 <td style="text-align: left;">장영신</td>
 <td name="sumA_target" style="text-align: right;">35</td>
 <td name="sumB_target" style="text-align: right;">37</td>
 <td name="sumC_target" style="text-align: right;">-2</td>
 <td style="text-align: right;">6,198</td>
 <td style="text-align: right;">5,589</td>
 <td style="text-align: right;">610</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에스케이</td>
 <td style="text-align: left;">최태원</td>
 <td name="sumA_target" style="text-align: right;">186</td>
 <td name="sumB_target" style="text-align: right;">148</td>
 <td name="sumC_target" style="text-align: right;">38</td>
 <td style="text-align: right;">291,969</td>
 <td style="text-align: right;">239,530</td>
 <td style="text-align: right;">52,439</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에쓰-오일</td>
 <td style="text-align: left;">에쓰-오일(주)</td>
 <td name="sumA_target" style="text-align: right;">2</td>
 <td name="sumB_target" style="text-align: right;">2</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">18,789</td>
 <td style="text-align: right;">15,795</td>
 <td style="text-align: right;">2,994</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에이치디씨</td>
 <td style="text-align: left;">정몽규</td>
 <td name="sumA_target" style="text-align: right;">34</td>
 <td name="sumB_target" style="text-align: right;">29</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">15,122</td>
 <td style="text-align: right;">13,549</td>
 <td style="text-align: right;">1,573</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에이치엠엠</td>
 <td style="text-align: left;">에이치엠엠(주)</td>
 <td name="sumA_target" style="text-align: right;">4</td>
 <td name="sumB_target" style="text-align: right;">4</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">17,767</td>
 <td style="text-align: right;">8,789</td>
 <td style="text-align: right;">8,978</td>
 </tr>,
 <tr>
 <td style="text-align: left;">엘에스</td>
 <td style="text-align: left;">구자은</td>
 <td name="sumA_target" style="text-align: right;">58</td>
 <td name="sumB_target" style="text-align: right;">58</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">26,270</td>
 <td style="text-align: right;">25,243</td>
 <td style="text-align: right;">1,026</td>
 </tr>,
 <tr>
 <td style="text-align: left;">엘지</td>
 <td style="text-align: left;">구광모</td>
 <td name="sumA_target" style="text-align: right;">73</td>
 <td name="sumB_target" style="text-align: right;">70</td>
 <td name="sumC_target" style="text-align: right;">3</td>
 <td style="text-align: right;">167,501</td>
 <td style="text-align: right;">151,322</td>
 <td style="text-align: right;">16,179</td>
 </tr>,
 <tr>
 <td style="text-align: left;">엠디엠</td>
 <td style="text-align: left;">문주현</td>
 <td name="sumA_target" style="text-align: right;">16</td>
 <td name="sumB_target" style="text-align: right;">22</td>
 <td name="sumC_target" style="text-align: right;">-6</td>
 <td style="text-align: right;">6,795</td>
 <td style="text-align: right;">5,256</td>
 <td style="text-align: right;">1,539</td>
 </tr>,
 <tr>
 <td style="text-align: left;">영풍</td>
 <td style="text-align: left;">장형진</td>
 <td name="sumA_target" style="text-align: right;">26</td>
 <td name="sumB_target" style="text-align: right;">27</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">14,632</td>
 <td style="text-align: right;">13,170</td>
 <td style="text-align: right;">1,461</td>
 </tr>,
 <tr>
 <td style="text-align: left;">오씨아이</td>
 <td style="text-align: left;">이우현</td>
 <td name="sumA_target" style="text-align: right;">22</td>
 <td name="sumB_target" style="text-align: right;">18</td>
 <td name="sumC_target" style="text-align: right;">4</td>
 <td style="text-align: right;">10,948</td>
 <td style="text-align: right;">9,815</td>
 <td style="text-align: right;">1,133</td>
 </tr>,
 <tr>
 <td style="text-align: left;">유진</td>
 <td style="text-align: left;">유경선</td>
 <td name="sumA_target" style="text-align: right;">57</td>
 <td name="sumB_target" style="text-align: right;">52</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">5,429</td>
 <td style="text-align: right;">5,528</td>
 <td style="text-align: right;">-100</td>
 </tr>,
 <tr>
 <td style="text-align: left;">이랜드</td>
 <td style="text-align: left;">박성수</td>
 <td name="sumA_target" style="text-align: right;">31</td>
 <td name="sumB_target" style="text-align: right;">33</td>
 <td name="sumC_target" style="text-align: right;">-2</td>
 <td style="text-align: right;">10,034</td>
 <td style="text-align: right;">9,509</td>
 <td style="text-align: right;">525</td>
 </tr>,
 <tr>
 <td style="text-align: left;">장금상선</td>
 <td style="text-align: left;">정태순</td>
 <td name="sumA_target" style="text-align: right;">30</td>
 <td name="sumB_target" style="text-align: right;">19</td>
 <td name="sumC_target" style="text-align: right;">11</td>
 <td style="text-align: right;">9,334</td>
 <td style="text-align: right;">6,263</td>
 <td style="text-align: right;">3,071</td>
 </tr>,
 <tr>
 <td style="text-align: left;">중앙</td>
 <td style="text-align: left;">홍석현</td>
 <td name="sumA_target" style="text-align: right;">55</td>
 <td name="sumB_target" style="text-align: right;">56</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">5,968</td>
 <td style="text-align: right;">5,014</td>
 <td style="text-align: right;">955</td>
 </tr>,
 <tr>
 <td style="text-align: left;">중흥건설</td>
 <td style="text-align: left;">정창선</td>
 <td name="sumA_target" style="text-align: right;">55</td>
 <td name="sumB_target" style="text-align: right;">37</td>
 <td name="sumC_target" style="text-align: right;">18</td>
 <td style="text-align: right;">20,292</td>
 <td style="text-align: right;">9,207</td>
 <td style="text-align: right;">11,085</td>
 </tr>,
 <tr>
 <td style="text-align: left;">지에스</td>
 <td style="text-align: left;">허창수</td>
 <td name="sumA_target" style="text-align: right;">93</td>
 <td name="sumB_target" style="text-align: right;">80</td>
 <td name="sumC_target" style="text-align: right;">13</td>
 <td style="text-align: right;">76,804</td>
 <td style="text-align: right;">67,677</td>
 <td style="text-align: right;">9,126</td>
 </tr>,
 <tr>
 <td style="text-align: left;">카카오</td>
 <td style="text-align: left;">김범수</td>
 <td name="sumA_target" style="text-align: right;">136</td>
 <td name="sumB_target" style="text-align: right;">118</td>
 <td name="sumC_target" style="text-align: right;">18</td>
 <td style="text-align: right;">32,216</td>
 <td style="text-align: right;">19,952</td>
 <td style="text-align: right;">12,264</td>
 </tr>,
 <tr>
 <td style="text-align: left;">케이씨씨</td>
 <td style="text-align: left;">정몽진</td>
 <td name="sumA_target" style="text-align: right;">14</td>
 <td name="sumB_target" style="text-align: right;">18</td>
 <td name="sumC_target" style="text-align: right;">-4</td>
 <td style="text-align: right;">12,632</td>
 <td style="text-align: right;">12,277</td>
 <td style="text-align: right;">355</td>
 </tr>,
 <tr>
 <td style="text-align: left;">케이티</td>
 <td style="text-align: left;">(주)케이티</td>
 <td name="sumA_target" style="text-align: right;">50</td>
 <td name="sumB_target" style="text-align: right;">48</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">42,090</td>
 <td style="text-align: right;">37,701</td>
 <td style="text-align: right;">4,389</td>
 </tr>,
 <tr>
 <td style="text-align: left;">케이티앤지</td>
 <td style="text-align: left;">(주)케이티앤지</td>
 <td name="sumA_target" style="text-align: right;">12</td>
 <td name="sumB_target" style="text-align: right;">10</td>

#### implicitly wait 사용하기 <br>
주의!) 거의사용하지 않음

In [73]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [72]:

driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더
driver.implicitly_wait(time_to_wait=5) #반드시 제일 상단에 나와야햠 드라이버 모든상황에 사용 #화면 layout 기준이기에 잘설정해야함
driver.get(url="https://www.egroup.go.kr/egps/wi/stat/kap/affltsAssetsTotamtList.do")
bs = BeautifulSoup(driver.page_source, 'lxml')  #페이지에 있는 모든소스를 가져온다

C:\Users\user\AppData\Local\Temp/ipykernel_24008/425343970.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더

In [71]:

bs.select('div#resultListDiv')[0].select('tr') #selenium은 모든 페이지의 내용을 가져올수있다

[]

#### explicitly wait <br>
(자주사용함)

In [83]:
driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더
driver.get(url="https://www.egroup.go.kr/egps/wi/stat/kap/affltsAssetsTotamtList.do")
WebDriverWait(driver, 5).until(
        EC.element_to_be_clickable((By.XPATH , '/html/body/div[2]/div[3]/div[3]/div/form/div/div[2]/div/div/div/table/tbody/tr[1]/td[3]')))
bs = BeautifulSoup(driver.page_source, 'lxml')

C:\Users\user\AppData\Local\Temp/ipykernel_24008/1653783288.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='./chromedriver.exe') # executable_path: chromedriver path #..바로 앞에 있는 폴더

In [84]:
bs.select('div#resultListDiv')[0].select('tr') #selenium은 모든 페이지의 내용을 가져올수있다

[<tr>
 <th rowspan="2" scope="colgroup">구분</th>
 <th rowspan="2" scope="colgroup">기업집단명</th>
 <th rowspan="2" scope="colgroup">동일인</th>
 <th colspan="3" scope="colgroup">계열회사 수</th>
 <th colspan="3" scope="colgroup">자산총액</th>
 </tr>,
 <tr>
 <th scope="colgroup">202205</th>
 <th scope="colgroup">202105</th>
 <th scope="colgroup">증감</th>
 <th scope="colgroup">202205</th>
 <th scope="colgroup">202105</th>
 <th scope="colgroup">증감</th>
 </tr>,
 <tr>
 <td name="gbnTd" rowspan="68">계속지정집단</td>
 <td style="text-align: left;">DB</td>
 <td style="text-align: left;">김준기</td>
 <td name="sumA_target" style="text-align: right;">20</td>
 <td name="sumB_target" style="text-align: right;">21</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">11,260</td>
 <td style="text-align: right;">10,366</td>
 <td style="text-align: right;">893</td>
 </tr>,
 <tr>
 <td style="text-align: left;">DL</td>
 <td style="text-align: left;">이준용</td>
 <td name="sumA_target" style="text-align: right;">42</td>
 <td name="sumB_target" style="text-align: right;">36</td>
 <td name="sumC_target" style="text-align: right;">6</td>
 <td style="text-align: right;">24,766</td>
 <td style="text-align: right;">19,627</td>
 <td style="text-align: right;">5,140</td>
 </tr>,
 <tr>
 <td style="text-align: left;">SM</td>
 <td style="text-align: left;">우오현</td>
 <td name="sumA_target" style="text-align: right;">63</td>
 <td name="sumB_target" style="text-align: right;">58</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">13,663</td>
 <td style="text-align: right;">10,450</td>
 <td style="text-align: right;">3,213</td>
 </tr>,
 <tr>
 <td style="text-align: left;">교보생명보험</td>
 <td style="text-align: left;">신창재</td>
 <td name="sumA_target" style="text-align: right;">14</td>
 <td name="sumB_target" style="text-align: right;">12</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">13,817</td>
 <td style="text-align: right;">14,413</td>
 <td style="text-align: right;">-596</td>
 </tr>,
 <tr>
 <td style="text-align: left;">금호석유화학</td>
 <td style="text-align: left;">박찬구</td>
 <td name="sumA_target" style="text-align: right;">13</td>
 <td name="sumB_target" style="text-align: right;">15</td>
 <td name="sumC_target" style="text-align: right;">-2</td>
 <td style="text-align: right;">9,608</td>
 <td style="text-align: right;">6,665</td>
 <td style="text-align: right;">2,943</td>
 </tr>,
 <tr>
 <td style="text-align: left;">금호아시아나</td>
 <td style="text-align: left;">박삼구</td>
 <td name="sumA_target" style="text-align: right;">32</td>
 <td name="sumB_target" style="text-align: right;">27</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">17,627</td>
 <td style="text-align: right;">17,442</td>
 <td style="text-align: right;">185</td>
 </tr>,
 <tr>
 <td style="text-align: left;">네이버</td>
 <td style="text-align: left;">이해진</td>
 <td name="sumA_target" style="text-align: right;">54</td>
 <td name="sumB_target" style="text-align: right;">45</td>
 <td name="sumC_target" style="text-align: right;">9</td>
 <td style="text-align: right;">19,220</td>
 <td style="text-align: right;">13,584</td>
 <td style="text-align: right;">5,636</td>
 </tr>,
 <tr>
 <td style="text-align: left;">넥슨</td>
 <td style="text-align: left;">유정현</td>
 <td name="sumA_target" style="text-align: right;">18</td>
 <td name="sumB_target" style="text-align: right;">18</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">11,261</td>
 <td style="text-align: right;">11,998</td>
 <td style="text-align: right;">-736</td>
 </tr>,
 <tr>
 <td style="text-align: left;">넷마블</td>
 <td style="text-align: left;">방준혁</td>
 <td name="sumA_target" style="text-align: right;">30</td>
 <td name="sumB_target" style="text-align: right;">23</td>
 <td name="sumC_target" style="text-align: right;">7</td>
 <td style="text-align: right;">13,303</td>
 <td style="text-align: right;">10,703</td>
 <td style="text-align: right;">2,600</td>
 </tr>,
 <tr>
 <td style="text-align: left;">농협</td>
 <td style="text-align: left;">농업협동조합중앙회</td>
 <td name="sumA_target" style="text-align: right;">53</td>
 <td name="sumB_target" style="text-align: right;">58</td>
 <td name="sumC_target" style="text-align: right;">-5</td>
 <td style="text-align: right;">66,962</td>
 <td style="text-align: right;">63,552</td>
 <td style="text-align: right;">3,411</td>
 </tr>,
 <tr>
 <td style="text-align: left;">다우키움</td>
 <td style="text-align: left;">김익래</td>
 <td name="sumA_target" style="text-align: right;">48</td>
 <td name="sumB_target" style="text-align: right;">45</td>
 <td name="sumC_target" style="text-align: right;">3</td>
 <td style="text-align: right;">8,505</td>
 <td style="text-align: right;">6,593</td>
 <td style="text-align: right;">1,912</td>
 </tr>,
 <tr>
 <td style="text-align: left;">대방건설</td>
 <td style="text-align: left;">구교운</td>
 <td name="sumA_target" style="text-align: right;">45</td>
 <td name="sumB_target" style="text-align: right;">43</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">6,184</td>
 <td style="text-align: right;">5,326</td>
 <td style="text-align: right;">858</td>
 </tr>,
 <tr>
 <td style="text-align: left;">대우조선해양</td>
 <td style="text-align: left;">대우조선해양(주)</td>
 <td name="sumA_target" style="text-align: right;">4</td>
 <td name="sumB_target" style="text-align: right;">5</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">11,415</td>
 <td style="text-align: right;">11,375</td>
 <td style="text-align: right;">39</td>
 </tr>,
 <tr>
 <td style="text-align: left;">동국제강</td>
 <td style="text-align: left;">장세주</td>
 <td name="sumA_target" style="text-align: right;">11</td>
 <td name="sumB_target" style="text-align: right;">11</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">6,711</td>
 <td style="text-align: right;">5,956</td>
 <td style="text-align: right;">754</td>
 </tr>,
 <tr>
 <td style="text-align: left;">동원</td>
 <td style="text-align: left;">김재철</td>
 <td name="sumA_target" style="text-align: right;">26</td>
 <td name="sumB_target" style="text-align: right;">26</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">9,281</td>
 <td style="text-align: right;">8,458</td>
 <td style="text-align: right;">823</td>
 </tr>,
 <tr>
 <td style="text-align: left;">두산</td>
 <td style="text-align: left;">박정원</td>
 <td name="sumA_target" style="text-align: right;">21</td>
 <td name="sumB_target" style="text-align: right;">22</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">26,334</td>
 <td style="text-align: right;">29,659</td>
 <td style="text-align: right;">-3,325</td>
 </tr>,
 <tr>
 <td style="text-align: left;">롯데</td>
 <td style="text-align: left;">신동빈</td>
 <td name="sumA_target" style="text-align: right;">85</td>
 <td name="sumB_target" style="text-align: right;">86</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">121,589</td>
 <td style="text-align: right;">117,781</td>
 <td style="text-align: right;">3,808</td>
 </tr>,
 <tr>
 <td style="text-align: left;">미래에셋</td>
 <td style="text-align: left;">박현주</td>
 <td name="sumA_target" style="text-align: right;">40</td>
 <td name="sumB_target" style="text-align: right;">38</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">20,231</td>
 <td style="text-align: right;">19,333</td>
 <td style="text-align: right;">897</td>
 </tr>,
 <tr>
 <td style="text-align: left;">반도홀딩스</td>
 <td style="text-align: left;">권홍사</td>
 <td name="sumA_target" style="text-align: right;">25</td>
 <td name="sumB_target" style="text-align: right;">28</td>
 <td name="sumC_target" style="text-align: right;">-3</td>
 <td style="text-align: right;">5,679</td>
 <td style="text-align: right;">5,585</td>
 <td style="text-align: right;">93</td>
 </tr>,
 <tr>
 <td style="text-align: left;">부영</td>
 <td style="text-align: left;">이중근</td>
 <td name="sumA_target" style="text-align: right;">22</td>
 <td name="sumB_target" style="text-align: right;">23</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">21,736</td>
 <td style="text-align: right;">23,321</td>
 <td style="text-align: right;">-1,585</td>
 </tr>,
 <tr>
 <td style="text-align: left;">삼성</td>
 <td style="text-align: left;">이재용</td>
 <td name="sumA_target" style="text-align: right;">60</td>
 <td name="sumB_target" style="text-align: right;">59</td>
 <td name="sumC_target" style="text-align: right;">1</td>
 <td style="text-align: right;">483,919</td>
 <td style="text-align: right;">457,305</td>
 <td style="text-align: right;">26,614</td>
 </tr>,
 <tr>
 <td style="text-align: left;">삼양</td>
 <td style="text-align: left;">김윤</td>
 <td name="sumA_target" style="text-align: right;">12</td>
 <td name="sumB_target" style="text-align: right;">11</td>
 <td name="sumC_target" style="text-align: right;">1</td>
 <td style="text-align: right;">6,247</td>
 <td style="text-align: right;">5,412</td>
 <td style="text-align: right;">835</td>
 </tr>,
 <tr>
 <td style="text-align: left;">삼천리</td>
 <td style="text-align: left;">이만득</td>
 <td name="sumA_target" style="text-align: right;">44</td>
 <td name="sumB_target" style="text-align: right;">42</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">8,551</td>
 <td style="text-align: right;">7,841</td>
 <td style="text-align: right;">709</td>
 </tr>,
 <tr>
 <td style="text-align: left;">세아</td>
 <td style="text-align: left;">이순형</td>
 <td name="sumA_target" style="text-align: right;">26</td>
 <td name="sumB_target" style="text-align: right;">29</td>
 <td name="sumC_target" style="text-align: right;">-3</td>
 <td style="text-align: right;">10,791</td>
 <td style="text-align: right;">9,470</td>
 <td style="text-align: right;">1,321</td>
 </tr>,
 <tr>
 <td style="text-align: left;">셀트리온</td>
 <td style="text-align: left;">서정진</td>
 <td name="sumA_target" style="text-align: right;">7</td>
 <td name="sumB_target" style="text-align: right;">8</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">14,576</td>
 <td style="text-align: right;">14,855</td>
 <td style="text-align: right;">-279</td>
 </tr>,
 <tr>
 <td style="text-align: left;">신세계</td>
 <td style="text-align: left;">이명희</td>
 <td name="sumA_target" style="text-align: right;">53</td>
 <td name="sumB_target" style="text-align: right;">45</td>
 <td name="sumC_target" style="text-align: right;">8</td>
 <td style="text-align: right;">61,055</td>
 <td style="text-align: right;">46,409</td>
 <td style="text-align: right;">14,645</td>
 </tr>,
 <tr>
 <td style="text-align: left;">씨제이</td>
 <td style="text-align: left;">이재현</td>
 <td name="sumA_target" style="text-align: right;">85</td>
 <td name="sumB_target" style="text-align: right;">79</td>
 <td name="sumC_target" style="text-align: right;">6</td>
 <td style="text-align: right;">36,925</td>
 <td style="text-align: right;">34,676</td>
 <td style="text-align: right;">2,249</td>
 </tr>,
 <tr>
 <td style="text-align: left;">아모레퍼시픽</td>
 <td style="text-align: left;">서경배</td>
 <td name="sumA_target" style="text-align: right;">13</td>
 <td name="sumB_target" style="text-align: right;">14</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">8,388</td>
 <td style="text-align: right;">8,009</td>
 <td style="text-align: right;">379</td>
 </tr>,
 <tr>
 <td style="text-align: left;">아이에스지주</td>
 <td style="text-align: left;">권혁운</td>
 <td name="sumA_target" style="text-align: right;">53</td>
 <td name="sumB_target" style="text-align: right;">46</td>
 <td name="sumC_target" style="text-align: right;">7</td>
 <td style="text-align: right;">5,343</td>
 <td style="text-align: right;">5,190</td>
 <td style="text-align: right;">153</td>
 </tr>,
 <tr>
 <td style="text-align: left;">애경</td>
 <td style="text-align: left;">장영신</td>
 <td name="sumA_target" style="text-align: right;">35</td>
 <td name="sumB_target" style="text-align: right;">37</td>
 <td name="sumC_target" style="text-align: right;">-2</td>
 <td style="text-align: right;">6,198</td>
 <td style="text-align: right;">5,589</td>
 <td style="text-align: right;">610</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에스케이</td>
 <td style="text-align: left;">최태원</td>
 <td name="sumA_target" style="text-align: right;">186</td>
 <td name="sumB_target" style="text-align: right;">148</td>
 <td name="sumC_target" style="text-align: right;">38</td>
 <td style="text-align: right;">291,969</td>
 <td style="text-align: right;">239,530</td>
 <td style="text-align: right;">52,439</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에쓰-오일</td>
 <td style="text-align: left;">에쓰-오일(주)</td>
 <td name="sumA_target" style="text-align: right;">2</td>
 <td name="sumB_target" style="text-align: right;">2</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">18,789</td>
 <td style="text-align: right;">15,795</td>
 <td style="text-align: right;">2,994</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에이치디씨</td>
 <td style="text-align: left;">정몽규</td>
 <td name="sumA_target" style="text-align: right;">34</td>
 <td name="sumB_target" style="text-align: right;">29</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">15,122</td>
 <td style="text-align: right;">13,549</td>
 <td style="text-align: right;">1,573</td>
 </tr>,
 <tr>
 <td style="text-align: left;">에이치엠엠</td>
 <td style="text-align: left;">에이치엠엠(주)</td>
 <td name="sumA_target" style="text-align: right;">4</td>
 <td name="sumB_target" style="text-align: right;">4</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">17,767</td>
 <td style="text-align: right;">8,789</td>
 <td style="text-align: right;">8,978</td>
 </tr>,
 <tr>
 <td style="text-align: left;">엘에스</td>
 <td style="text-align: left;">구자은</td>
 <td name="sumA_target" style="text-align: right;">58</td>
 <td name="sumB_target" style="text-align: right;">58</td>
 <td name="sumC_target" style="text-align: right;">0</td>
 <td style="text-align: right;">26,270</td>
 <td style="text-align: right;">25,243</td>
 <td style="text-align: right;">1,026</td>
 </tr>,
 <tr>
 <td style="text-align: left;">엘지</td>
 <td style="text-align: left;">구광모</td>
 <td name="sumA_target" style="text-align: right;">73</td>
 <td name="sumB_target" style="text-align: right;">70</td>
 <td name="sumC_target" style="text-align: right;">3</td>
 <td style="text-align: right;">167,501</td>
 <td style="text-align: right;">151,322</td>
 <td style="text-align: right;">16,179</td>
 </tr>,
 <tr>
 <td style="text-align: left;">엠디엠</td>
 <td style="text-align: left;">문주현</td>
 <td name="sumA_target" style="text-align: right;">16</td>
 <td name="sumB_target" style="text-align: right;">22</td>
 <td name="sumC_target" style="text-align: right;">-6</td>
 <td style="text-align: right;">6,795</td>
 <td style="text-align: right;">5,256</td>
 <td style="text-align: right;">1,539</td>
 </tr>,
 <tr>
 <td style="text-align: left;">영풍</td>
 <td style="text-align: left;">장형진</td>
 <td name="sumA_target" style="text-align: right;">26</td>
 <td name="sumB_target" style="text-align: right;">27</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">14,632</td>
 <td style="text-align: right;">13,170</td>
 <td style="text-align: right;">1,461</td>
 </tr>,
 <tr>
 <td style="text-align: left;">오씨아이</td>
 <td style="text-align: left;">이우현</td>
 <td name="sumA_target" style="text-align: right;">22</td>
 <td name="sumB_target" style="text-align: right;">18</td>
 <td name="sumC_target" style="text-align: right;">4</td>
 <td style="text-align: right;">10,948</td>
 <td style="text-align: right;">9,815</td>
 <td style="text-align: right;">1,133</td>
 </tr>,
 <tr>
 <td style="text-align: left;">유진</td>
 <td style="text-align: left;">유경선</td>
 <td name="sumA_target" style="text-align: right;">57</td>
 <td name="sumB_target" style="text-align: right;">52</td>
 <td name="sumC_target" style="text-align: right;">5</td>
 <td style="text-align: right;">5,429</td>
 <td style="text-align: right;">5,528</td>
 <td style="text-align: right;">-100</td>
 </tr>,
 <tr>
 <td style="text-align: left;">이랜드</td>
 <td style="text-align: left;">박성수</td>
 <td name="sumA_target" style="text-align: right;">31</td>
 <td name="sumB_target" style="text-align: right;">33</td>
 <td name="sumC_target" style="text-align: right;">-2</td>
 <td style="text-align: right;">10,034</td>
 <td style="text-align: right;">9,509</td>
 <td style="text-align: right;">525</td>
 </tr>,
 <tr>
 <td style="text-align: left;">장금상선</td>
 <td style="text-align: left;">정태순</td>
 <td name="sumA_target" style="text-align: right;">30</td>
 <td name="sumB_target" style="text-align: right;">19</td>
 <td name="sumC_target" style="text-align: right;">11</td>
 <td style="text-align: right;">9,334</td>
 <td style="text-align: right;">6,263</td>
 <td style="text-align: right;">3,071</td>
 </tr>,
 <tr>
 <td style="text-align: left;">중앙</td>
 <td style="text-align: left;">홍석현</td>
 <td name="sumA_target" style="text-align: right;">55</td>
 <td name="sumB_target" style="text-align: right;">56</td>
 <td name="sumC_target" style="text-align: right;">-1</td>
 <td style="text-align: right;">5,968</td>
 <td style="text-align: right;">5,014</td>
 <td style="text-align: right;">955</td>
 </tr>,
 <tr>
 <td style="text-align: left;">중흥건설</td>
 <td style="text-align: left;">정창선</td>
 <td name="sumA_target" style="text-align: right;">55</td>
 <td name="sumB_target" style="text-align: right;">37</td>
 <td name="sumC_target" style="text-align: right;">18</td>
 <td style="text-align: right;">20,292</td>
 <td style="text-align: right;">9,207</td>
 <td style="text-align: right;">11,085</td>
 </tr>,
 <tr>
 <td style="text-align: left;">지에스</td>
 <td style="text-align: left;">허창수</td>
 <td name="sumA_target" style="text-align: right;">93</td>
 <td name="sumB_target" style="text-align: right;">80</td>
 <td name="sumC_target" style="text-align: right;">13</td>
 <td style="text-align: right;">76,804</td>
 <td style="text-align: right;">67,677</td>
 <td style="text-align: right;">9,126</td>
 </tr>,
 <tr>
 <td style="text-align: left;">카카오</td>
 <td style="text-align: left;">김범수</td>
 <td name="sumA_target" style="text-align: right;">136</td>
 <td name="sumB_target" style="text-align: right;">118</td>
 <td name="sumC_target" style="text-align: right;">18</td>
 <td style="text-align: right;">32,216</td>
 <td style="text-align: right;">19,952</td>
 <td style="text-align: right;">12,264</td>
 </tr>,
 <tr>
 <td style="text-align: left;">케이씨씨</td>
 <td style="text-align: left;">정몽진</td>
 <td name="sumA_target" style="text-align: right;">14</td>
 <td name="sumB_target" style="text-align: right;">18</td>
 <td name="sumC_target" style="text-align: right;">-4</td>
 <td style="text-align: right;">12,632</td>
 <td style="text-align: right;">12,277</td>
 <td style="text-align: right;">355</td>
 </tr>,
 <tr>
 <td style="text-align: left;">케이티</td>
 <td style="text-align: left;">(주)케이티</td>
 <td name="sumA_target" style="text-align: right;">50</td>
 <td name="sumB_target" style="text-align: right;">48</td>
 <td name="sumC_target" style="text-align: right;">2</td>
 <td style="text-align: right;">42,090</td>
 <td style="text-align: right;">37,701</td>
 <td style="text-align: right;">4,389</td>
 </tr>,
 <tr>
 <td style="text-align: left;">케이티앤지</td>
 <td style="text-align: left;">(주)케이티앤지</td>
 <td name="sumA_target" style="text-align: right;">12</td>
 <td name="sumB_target" style="text-align: right;">10</td>